import prop1 from "../../assets/images/DummyImgs/1.jpg"

export const PropertiesData = [
    {
        "_id": "1",
        "title": "Merrick in Spring Way",
        "type": "Apartment",
        "status": "Rent",
        "price": 50000,
        "rooms": 4,
        "beds": 2,
        "country": "Nigeria",
        "city": "Akure",
        "address": "House5, Green Garage",
        "description": "Lounge Apartment",
        "image": prop1,
        "video": "",
    },
    {
        "_id": "2",
        "title": "Appapa way bridge",
        "type": "Apartment",
        "status": "Rent",
        "price": 75000,
        "rooms": 4,
        "beds": 2,
        "country": "Nigeria",
        "city": "Akure",
        "address": "House5, Green Garage",
        "description": "Lounge Apartment",
        "image": prop1,
        "video": "",
    },
    {
        "_id": "3",
        "title": "Merrick in Spring Way",
        "type": "Apartment",
        "status": "Rent",
        "price": 50000,
        "rooms": 4,
        "beds": 2,
        "country": "Nigeria",
        "city": "Akure",
        "address": "House5, Green Garage",
        "description": "Lounge Apartment",
        "image": prop1,
        "video": "",
    },
    {
        "_id": "4",
        "title": "Apapatapiti way",
        "type": "Apartment",
        "status": "Rent",
        "price": 200000,
        "rooms": 4,
        "beds": 2,
        "country": "Nigeria",
        "city": "Akure",
        "address": "House5, Green Garage",
        "description": "Lounge Apartment",
        "image": prop1,
        "video": "",
    },
    {
        "_id": "5",
        "title": "Grayce's and milky's lodge",
        "type": "Apartment",
        "status": "Rent",
        "price": 5649000,
        "rooms": 4,
        "beds": 2,
        "country": "Nigeria",
        "city": "Akure",
        "address": "House5, Green Garage",
        "description": "Lounge Apartment",
        "image": prop1,
        "video": "",
    },
    {
        "_id": "6",
        "title": "Solo in Spring",
        "type": "Apartment",
        "status": "Rent",
        "price": 58000,
        "rooms": 4,
        "beds": 2,
        "country": "Nigeria",
        "city": "Akure",
        "address": "House5, Green Garage",
        "description": "Lounge Apartment",
        "image": prop1,
        "video": "",
    },
]